/**
 * @file bg_sub.cpp
 * @brief Background subtraction tutorial sample code
 * @author Domenico D. Bloisi
 */

//Modified by Don Johnson using http://stackoverflow.com/questions/19221877/opencv-how-to-use-createbackgroundsubtractormog which provided modifications supplied by http://stackoverflow.com/users/1608646/terran

//opencv
#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/video/background_segm.hpp>
#include <opencv2/imgproc/types_c.h>
#include <opencv2/imgproc/imgproc.hpp>
//C
#include <stdio.h>
//C++
#include <iostream>
#include <sstream>

using namespace cv;
using namespace std;

//global variables
Mat frame; //current frame
Mat fgMaskMOG; //fg mask generated by MOG method
Mat fgMaskMOG2; //fg mask fg mask generated by MOG2 method
Ptr<BackgroundSubtractor> pMOG; //MOG Background subtractor
Ptr<BackgroundSubtractor> pMOG2; //MOG2 Background subtractor
int keyboard;

//function declarations
void help();
void processVideo(char* videoFilename, char* videoFilenameOut);
void processImages(char* firstFrameFilename);

void help()
{
    cout
    << "--------------------------------------------------------------------------"  << endl
    << "This program shows how to use background subtraction methods provided by "   << endl
    << " OpenCV. You can process both videos (-vid) and images (-img)."              << endl
    << endl
    << "Usage:"                                                                      << endl
    << "./bs {-vid <video filename>|-img <image filename>}"                          << endl
    << "for example: ./bs -vid video.avi"                                            << endl
    << "or: ./bs -img /data/images/1.png"                                            << endl
    << "--------------------------------------------------------------------------"  << endl
    << endl;
}

int main(int argc, char* argv[])
{
    //print help information
    help();
    
    //check for the input parameter correctness
    if(argc != 4) {
        cerr <<"Incorret input list" << endl;
        cerr <<"exiting..." << endl;
        return EXIT_FAILURE;
    }
    
    //create GUI windows
    namedWindow("Frame");
    namedWindow("FG Mask MOG");
    namedWindow("FG Mask MOG 2");
    
    //create Background Subtractor objects
    // Modified by Don Johnson
    int history=30;
    int nmixtures=5;
    double backgroundRatio=0.9;
    double noiseSigma=0;
    float varThreshold=16.0;
    bool bShadowDetection=false;

    pMOG= new BackgroundSubtractorMOG(history, nmixtures, backgroundRatio, noiseSigma); //MOG approach
    pMOG2 = new BackgroundSubtractorMOG2(history,varThreshold,bShadowDetection); //MOG2 approach
    
    char path[256],pathOut[256];
    strcpy(path, "/Users/donj/workspace/cs585/Lab8/Data/");
    strcat(path, argv[2]);
    strcpy(pathOut, "/Users/donj/workspace/cs585/Lab8/Data/");
    strcat(pathOut, argv[3]);
    if(strcmp(argv[1], "-vid") == 0) {
        //input data coming from a video
        processVideo(path,pathOut);
    }
    else if(strcmp(argv[1], "-img") == 0) {
        //input data coming from a sequence of images
        processImages(path);
    }
    else {
        //error in reading input parameters
        cerr <<"Please, check the input parameters." << endl;
        cerr <<"Exiting..." << endl;
        return EXIT_FAILURE;
    }
    //destroy GUI windows
    destroyAllWindows();
    return EXIT_SUCCESS;
}

void processVideo(char* videoFilename, char* videoFilenameOut) {
    //create the capture object
    // Modified by Don Johnson
    VideoCapture capture(videoFilename);
    double fps = capture.get(CV_CAP_PROP_FPS);
    int width = capture.get(CV_CAP_PROP_FRAME_WIDTH);
    int height = capture.get(CV_CAP_PROP_FRAME_HEIGHT);
    VideoWriter videoOut(videoFilenameOut,CV_FOURCC('m', 'p', '4', 'v'), fps, Size(width,height));
    if(!capture.isOpened()){
        //error in opening the video input
        cerr << "Unable to open video file: " << videoFilename << endl;
        exit(EXIT_FAILURE);
    }
    //read input data. ESC or 'q' for quitting
    while( (char)keyboard != 'q' && (char)keyboard != 27 ){
        //read the current frame
        if(!capture.read(frame)) {
            cerr << "Exiting..." << endl;
            exit(EXIT_FAILURE);
        }
        //update the background model
        // Modified by Don Johnson
        double learningRate=0.1;
        pMOG->operator()(frame, fgMaskMOG,learningRate);
        //pMOG2->operator()(frame, fgMaskMOG2,learningRate);
        
        //get the frame number and write it on the current frame
        stringstream ss;
        rectangle(frame, cv::Point(10, 2), cv::Point(100,20),
                  cv::Scalar(255,255,255), -1);
        ss << capture.get(CV_CAP_PROP_POS_FRAMES);
        if(0 && atoi(ss.str().c_str())>0)
        {
            pMOG->operator()(frame, fgMaskMOG);
            //pMOG2->operator()(frame, fgMaskMOG2);
        }
        string frameNumberString = ss.str();
        putText(frame, frameNumberString.c_str(), cv::Point(15, 15),
                FONT_HERSHEY_SIMPLEX, 0.5 , cv::Scalar(0,0,0));
        //show the current frame and the fg masks
        Mat temp;
        fgMaskMOG.copyTo(temp);
        cvtColor(temp, temp, CV_GRAY2BGR);
        videoOut << temp;
        cout<<"Frame "<<frameNumberString<<endl;
        imshow("Frame", frame);
        imshow("FG Mask MOG", fgMaskMOG);
        //imshow("FG Mask MOG 2", fgMaskMOG2);
        //get the input from the keyboard
        keyboard = waitKey( 30 );
    }
    //delete capture object
    videoOut.release();
    capture.release();
}

void processImages(char* fistFrameFilename) {
    //read the first file of the sequence
    frame = imread(fistFrameFilename);
    if(!frame.data){
        //error in opening the first image
        cerr << "Unable to open first image frame: " << fistFrameFilename << endl;
        exit(EXIT_FAILURE);
    }
    //current image filename
    string fn(fistFrameFilename);
    //read input data. ESC or 'q' for quitting
    while( (char)keyboard != 'q' && (char)keyboard != 27 ){
        //update the background model
        //ALSO HERE!!!!
        pMOG->operator()(frame, fgMaskMOG);
        pMOG2->operator()(frame, fgMaskMOG2);
        //get the frame number and write it on the current frame
        size_t index = fn.find_last_of("/");
        if(index == string::npos) {
            index = fn.find_last_of("\\");
        }
        size_t index2 = fn.find_last_of(".");
        string prefix = fn.substr(0,index+1);
        string suffix = fn.substr(index2);
        string frameNumberString = fn.substr(index+1, index2-index-1);
        istringstream iss(frameNumberString);
        int frameNumber = 0;
        iss >> frameNumber;
        rectangle(frame, cv::Point(10, 2), cv::Point(100,20),
                  cv::Scalar(255,255,255), -1);
        putText(frame, frameNumberString.c_str(), cv::Point(15, 15),
                FONT_HERSHEY_SIMPLEX, 0.5 , cv::Scalar(0,0,0));
        //show the current frame and the fg masks
        imshow("Frame", frame);
        imshow("FG Mask MOG", fgMaskMOG);
        imshow("FG Mask MOG 2", fgMaskMOG2);
        //get the input from the keyboard
        keyboard = waitKey( 30 );
        //search for the next image in the sequence
        ostringstream oss;
        oss << (frameNumber + 1);
        string nextFrameNumberString = oss.str();
        string nextFrameFilename = prefix + nextFrameNumberString + suffix;
        //read the next frame
        frame = imread(nextFrameFilename);
        if(!frame.data){
            //error in opening the next image in the sequence
            cerr << "Unable to open image frame: " << nextFrameFilename << endl;
            exit(EXIT_FAILURE);
        }
        //update the path of the current frame
        fn.assign(nextFrameFilename);
    }
}